[tool.poetry]
name = "The Core"
version = "0.1.0"
description = "The core of the software product on the backend side"
authors = ["Divider"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.0.1"
SQLAlchemy = "^1.4.32"
alembic = "^1.7.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
