"""Initial

Revision ID: 6fe99ae4bc06
Revises: 
Create Date: 2022-03-25 16:07:40.642797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe99ae4bc06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('compatibility', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['compatibility'], ['equipments.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_name'), 'parts', ['name'], unique=True)
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('compatibility', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['compatibility'], ['parts.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumables_id'), 'consumables', ['id'], unique=False)
    op.create_index(op.f('ix_consumables_name'), 'consumables', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumables_name'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_id'), table_name='consumables')
    op.drop_table('consumables')
    op.drop_index(op.f('ix_parts_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
